package com.topway.fine.model;

import android.os.Parcel;
import android.os.Parcelable;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSONException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Companys".
 */
public class Company implements Parcelable {

    private Long id;
    private String name;
    private String shortname;
    private String alpha;
    private String pinyin;
    private String abbr;
    private String address;
    private String telephone;
    private String mobile;
    private String fax;
    private String email;
    private String qq;
    private String man;
    private String memo;
    private String image;
    private Long hot;

    public Company() {
    }

    public Company(Long id) {
        this.id = id;
    }

    public Company(Long id, String name, String shortname, String alpha, String pinyin, String abbr, String address, String telephone, String mobile, String fax, String email, String qq, String man, String memo, String image, Long hot) {
        this.id = id;
        this.name = name;
        this.shortname = shortname;
        this.alpha = alpha;
        this.pinyin = pinyin;
        this.abbr = abbr;
        this.address = address;
        this.telephone = telephone;
        this.mobile = mobile;
        this.fax = fax;
        this.email = email;
        this.qq = qq;
        this.man = man;
        this.memo = memo;
        this.image = image;
        this.hot = hot;
    }

    public void setDefaultValue() {
        if (this.id == null )
           this.id = new Long(0);
        if (this.name == null )
           this.name = "";
        if (this.shortname == null )
           this.shortname = "";
        if (this.alpha == null )
           this.alpha = "";
        if (this.pinyin == null )
           this.pinyin = "";
        if (this.abbr == null )
           this.abbr = "";
        if (this.address == null )
           this.address = "";
        if (this.telephone == null )
           this.telephone = "";
        if (this.mobile == null )
           this.mobile = "";
        if (this.fax == null )
           this.fax = "";
        if (this.email == null )
           this.email = "";
        if (this.qq == null )
           this.qq = "";
        if (this.man == null )
           this.man = "";
        if (this.memo == null )
           this.memo = "";
        if (this.image == null )
           this.image = "";
        if (this.hot == null )
           this.hot = new Long(0);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getShortname() {
        return shortname;
    }

    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    public String getAlpha() {
        return alpha;
    }

    public void setAlpha(String alpha) {
        this.alpha = alpha;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public String getAbbr() {
        return abbr;
    }

    public void setAbbr(String abbr) {
        this.abbr = abbr;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getQq() {
        return qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    public String getMan() {
        return man;
    }

    public void setMan(String man) {
        this.man = man;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Long getHot() {
        return hot;
    }

    public void setHot(Long hot) {
        this.hot = hot;
    }


    //Parcelable
    protected Company (Parcel in) {
        id = in.readLong();
        name = in.readString();
        shortname = in.readString();
        alpha = in.readString();
        pinyin = in.readString();
        abbr = in.readString();
        address = in.readString();
        telephone = in.readString();
        mobile = in.readString();
        fax = in.readString();
        email = in.readString();
        qq = in.readString();
        man = in.readString();
        memo = in.readString();
        image = in.readString();
        hot = in.readLong();
    }

    public static final Creator<Company> CREATOR = new Creator<Company>() {
        @Override
        public Company createFromParcel(Parcel in) {
            return new Company(in);
        }

        @Override
        public Company[] newArray(int size) {
            return new Company[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(id);
        dest.writeString(name);
        dest.writeString(shortname);
        dest.writeString(alpha);
        dest.writeString(pinyin);
        dest.writeString(abbr);
        dest.writeString(address);
        dest.writeString(telephone);
        dest.writeString(mobile);
        dest.writeString(fax);
        dest.writeString(email);
        dest.writeString(qq);
        dest.writeString(man);
        dest.writeString(memo);
        dest.writeString(image);
        dest.writeLong(hot);
    }
    //Parcelable END

    //JsonSerializable
    public static Company fromJson(JSONObject jsonObject) throws JSONException {
        Company domain = new Company();

        domain.id = jsonObject.getLong("id");
        domain.name = jsonObject.getString("NAME");
        domain.shortname = jsonObject.getString("SHORTNAME");
        domain.alpha = jsonObject.getString("ALPHA");
        domain.pinyin = jsonObject.getString("PINYIN");
        domain.abbr = jsonObject.getString("ABBR");
        domain.address = jsonObject.getString("ADDRESS");
        domain.telephone = jsonObject.getString("TELEPHONE");
        domain.mobile = jsonObject.getString("MOBILE");
        domain.fax = jsonObject.getString("FAX");
        domain.email = jsonObject.getString("EMAIL");
        domain.qq = jsonObject.getString("QQ");
        domain.man = jsonObject.getString("MAN");
        domain.memo = jsonObject.getString("MEMO");
        domain.image = jsonObject.getString("IMAGE");
        domain.hot = jsonObject.getLong("HOT");

        return domain;
    }

    public static String toJson(Company obj) throws JSONException {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("id",obj.id);
        jsonObject.put("NAME",obj.name);
        jsonObject.put("SHORTNAME",obj.shortname);
        jsonObject.put("ALPHA",obj.alpha);
        jsonObject.put("PINYIN",obj.pinyin);
        jsonObject.put("ABBR",obj.abbr);
        jsonObject.put("ADDRESS",obj.address);
        jsonObject.put("TELEPHONE",obj.telephone);
        jsonObject.put("MOBILE",obj.mobile);
        jsonObject.put("FAX",obj.fax);
        jsonObject.put("EMAIL",obj.email);
        jsonObject.put("QQ",obj.qq);
        jsonObject.put("MAN",obj.man);
        jsonObject.put("MEMO",obj.memo);
        jsonObject.put("IMAGE",obj.image);
        jsonObject.put("HOT",obj.hot);
        return jsonObject.toString();
    }
    //JsonSerializable END

}
