package com.topway.fine.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ContactWays".
 */
public class ContactWay {

    private Long id;
    private Long tableId;
    private Long primaryId;
    private Long way;
    private String number;

    public ContactWay() {
    }

    public ContactWay(Long id) {
        this.id = id;
    }

    public ContactWay(Long id, Long tableId, Long primaryId, Long way, String number) {
        this.id = id;
        this.tableId = tableId;
        this.primaryId = primaryId;
        this.way = way;
        this.number = number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTableId() {
        return tableId;
    }

    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }

    public Long getPrimaryId() {
        return primaryId;
    }

    public void setPrimaryId(Long primaryId) {
        this.primaryId = primaryId;
    }

    public Long getWay() {
        return way;
    }

    public void setWay(Long way) {
        this.way = way;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

}
