package com.topway.fine.model;

import android.os.Parcel;
import android.os.Parcelable;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSONException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Contacts".
 */
public class Contact implements Parcelable {

    private Long id;
    private Long name;
    private Long sex;
    private Long companyId;
    private String memo;
    private String image;
    private Long hot;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, Long name, Long sex, Long companyId, String memo, String image, Long hot) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.companyId = companyId;
        this.memo = memo;
        this.image = image;
        this.hot = hot;
    }

    public void setDefaultValue() {
        if (this.id == null )
           this.id = new Long(0);
        if (this.name == null )
           this.name = new Long(0);
        if (this.sex == null )
           this.sex = new Long(0);
        if (this.companyId == null )
           this.companyId = new Long(0);
        if (this.memo == null )
           this.memo = "";
        if (this.image == null )
           this.image = "";
        if (this.hot == null )
           this.hot = new Long(0);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getName() {
        return name;
    }

    public void setName(Long name) {
        this.name = name;
    }

    public Long getSex() {
        return sex;
    }

    public void setSex(Long sex) {
        this.sex = sex;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Long getHot() {
        return hot;
    }

    public void setHot(Long hot) {
        this.hot = hot;
    }


    //Parcelable
    protected Contact (Parcel in) {
        id = in.readLong();
        name = in.readLong();
        sex = in.readLong();
        companyId = in.readLong();
        memo = in.readString();
        image = in.readString();
        hot = in.readLong();
    }

    public static final Creator<Contact> CREATOR = new Creator<Contact>() {
        @Override
        public Contact createFromParcel(Parcel in) {
            return new Contact(in);
        }

        @Override
        public Contact[] newArray(int size) {
            return new Contact[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(id);
        dest.writeLong(name);
        dest.writeLong(sex);
        dest.writeLong(companyId);
        dest.writeString(memo);
        dest.writeString(image);
        dest.writeLong(hot);
    }
    //Parcelable END

    //JsonSerializable
    public static Contact fromJson(JSONObject jsonObject) throws JSONException {
        Contact domain = new Contact();

        domain.id = jsonObject.getLong("id");
        domain.name = jsonObject.getLong("NAME");
        domain.sex = jsonObject.getLong("SEX");
        domain.companyId = jsonObject.getLong("COMPANY_ID");
        domain.memo = jsonObject.getString("MEMO");
        domain.image = jsonObject.getString("IMAGE");
        domain.hot = jsonObject.getLong("HOT");

        return domain;
    }

    public static String toJson(Contact obj) throws JSONException {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("id",obj.id);
        jsonObject.put("NAME",obj.name);
        jsonObject.put("SEX",obj.sex);
        jsonObject.put("COMPANY_ID",obj.companyId);
        jsonObject.put("MEMO",obj.memo);
        jsonObject.put("IMAGE",obj.image);
        jsonObject.put("HOT",obj.hot);
        return jsonObject.toString();
    }
    //JsonSerializable END

}
