package com.topway.fine.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.topway.fine.model.Table;
import com.topway.fine.model.Sequnce;
import com.topway.fine.model.Company;
import com.topway.fine.model.Zone;
import com.topway.fine.model.Category;
import com.topway.fine.model.CategoryGroup;
import com.topway.fine.model.Brand;
import com.topway.fine.model.Generic;
import com.topway.fine.model.Engine;
import com.topway.fine.model.SerieEngines;
import com.topway.fine.model.Manufacturer;
import com.topway.fine.model.Serie;
import com.topway.fine.model.Part;
import com.topway.fine.model.Product;
import com.topway.fine.model.Supplier;
import com.topway.fine.model.Contact;
import com.topway.fine.model.Link;
import com.topway.fine.model.Photo;
import com.topway.fine.model.Dictionary;

import com.topway.fine.model.TableDao;
import com.topway.fine.model.SequnceDao;
import com.topway.fine.model.CompanyDao;
import com.topway.fine.model.ZoneDao;
import com.topway.fine.model.CategoryDao;
import com.topway.fine.model.CategoryGroupDao;
import com.topway.fine.model.BrandDao;
import com.topway.fine.model.GenericDao;
import com.topway.fine.model.EngineDao;
import com.topway.fine.model.SerieEnginesDao;
import com.topway.fine.model.ManufacturerDao;
import com.topway.fine.model.SerieDao;
import com.topway.fine.model.PartDao;
import com.topway.fine.model.ProductDao;
import com.topway.fine.model.SupplierDao;
import com.topway.fine.model.ContactDao;
import com.topway.fine.model.LinkDao;
import com.topway.fine.model.PhotoDao;
import com.topway.fine.model.DictionaryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tableDaoConfig;
    private final DaoConfig sequnceDaoConfig;
    private final DaoConfig companyDaoConfig;
    private final DaoConfig zoneDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig categoryGroupDaoConfig;
    private final DaoConfig brandDaoConfig;
    private final DaoConfig genericDaoConfig;
    private final DaoConfig engineDaoConfig;
    private final DaoConfig serieEnginesDaoConfig;
    private final DaoConfig manufacturerDaoConfig;
    private final DaoConfig serieDaoConfig;
    private final DaoConfig partDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig supplierDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig linkDaoConfig;
    private final DaoConfig photoDaoConfig;
    private final DaoConfig dictionaryDaoConfig;

    private final TableDao tableDao;
    private final SequnceDao sequnceDao;
    private final CompanyDao companyDao;
    private final ZoneDao zoneDao;
    private final CategoryDao categoryDao;
    private final CategoryGroupDao categoryGroupDao;
    private final BrandDao brandDao;
    private final GenericDao genericDao;
    private final EngineDao engineDao;
    private final SerieEnginesDao serieEnginesDao;
    private final ManufacturerDao manufacturerDao;
    private final SerieDao serieDao;
    private final PartDao partDao;
    private final ProductDao productDao;
    private final SupplierDao supplierDao;
    private final ContactDao contactDao;
    private final LinkDao linkDao;
    private final PhotoDao photoDao;
    private final DictionaryDao dictionaryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tableDaoConfig = daoConfigMap.get(TableDao.class).clone();
        tableDaoConfig.initIdentityScope(type);

        sequnceDaoConfig = daoConfigMap.get(SequnceDao.class).clone();
        sequnceDaoConfig.initIdentityScope(type);

        companyDaoConfig = daoConfigMap.get(CompanyDao.class).clone();
        companyDaoConfig.initIdentityScope(type);

        zoneDaoConfig = daoConfigMap.get(ZoneDao.class).clone();
        zoneDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        categoryGroupDaoConfig = daoConfigMap.get(CategoryGroupDao.class).clone();
        categoryGroupDaoConfig.initIdentityScope(type);

        brandDaoConfig = daoConfigMap.get(BrandDao.class).clone();
        brandDaoConfig.initIdentityScope(type);

        genericDaoConfig = daoConfigMap.get(GenericDao.class).clone();
        genericDaoConfig.initIdentityScope(type);

        engineDaoConfig = daoConfigMap.get(EngineDao.class).clone();
        engineDaoConfig.initIdentityScope(type);

        serieEnginesDaoConfig = daoConfigMap.get(SerieEnginesDao.class).clone();
        serieEnginesDaoConfig.initIdentityScope(type);

        manufacturerDaoConfig = daoConfigMap.get(ManufacturerDao.class).clone();
        manufacturerDaoConfig.initIdentityScope(type);

        serieDaoConfig = daoConfigMap.get(SerieDao.class).clone();
        serieDaoConfig.initIdentityScope(type);

        partDaoConfig = daoConfigMap.get(PartDao.class).clone();
        partDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        supplierDaoConfig = daoConfigMap.get(SupplierDao.class).clone();
        supplierDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        linkDaoConfig = daoConfigMap.get(LinkDao.class).clone();
        linkDaoConfig.initIdentityScope(type);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        dictionaryDaoConfig = daoConfigMap.get(DictionaryDao.class).clone();
        dictionaryDaoConfig.initIdentityScope(type);

        tableDao = new TableDao(tableDaoConfig, this);
        sequnceDao = new SequnceDao(sequnceDaoConfig, this);
        companyDao = new CompanyDao(companyDaoConfig, this);
        zoneDao = new ZoneDao(zoneDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        categoryGroupDao = new CategoryGroupDao(categoryGroupDaoConfig, this);
        brandDao = new BrandDao(brandDaoConfig, this);
        genericDao = new GenericDao(genericDaoConfig, this);
        engineDao = new EngineDao(engineDaoConfig, this);
        serieEnginesDao = new SerieEnginesDao(serieEnginesDaoConfig, this);
        manufacturerDao = new ManufacturerDao(manufacturerDaoConfig, this);
        serieDao = new SerieDao(serieDaoConfig, this);
        partDao = new PartDao(partDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        supplierDao = new SupplierDao(supplierDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        linkDao = new LinkDao(linkDaoConfig, this);
        photoDao = new PhotoDao(photoDaoConfig, this);
        dictionaryDao = new DictionaryDao(dictionaryDaoConfig, this);

        registerDao(Table.class, tableDao);
        registerDao(Sequnce.class, sequnceDao);
        registerDao(Company.class, companyDao);
        registerDao(Zone.class, zoneDao);
        registerDao(Category.class, categoryDao);
        registerDao(CategoryGroup.class, categoryGroupDao);
        registerDao(Brand.class, brandDao);
        registerDao(Generic.class, genericDao);
        registerDao(Engine.class, engineDao);
        registerDao(SerieEngines.class, serieEnginesDao);
        registerDao(Manufacturer.class, manufacturerDao);
        registerDao(Serie.class, serieDao);
        registerDao(Part.class, partDao);
        registerDao(Product.class, productDao);
        registerDao(Supplier.class, supplierDao);
        registerDao(Contact.class, contactDao);
        registerDao(Link.class, linkDao);
        registerDao(Photo.class, photoDao);
        registerDao(Dictionary.class, dictionaryDao);
    }
    
    public void clear() {
        tableDaoConfig.getIdentityScope().clear();
        sequnceDaoConfig.getIdentityScope().clear();
        companyDaoConfig.getIdentityScope().clear();
        zoneDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        categoryGroupDaoConfig.getIdentityScope().clear();
        brandDaoConfig.getIdentityScope().clear();
        genericDaoConfig.getIdentityScope().clear();
        engineDaoConfig.getIdentityScope().clear();
        serieEnginesDaoConfig.getIdentityScope().clear();
        manufacturerDaoConfig.getIdentityScope().clear();
        serieDaoConfig.getIdentityScope().clear();
        partDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        supplierDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        linkDaoConfig.getIdentityScope().clear();
        photoDaoConfig.getIdentityScope().clear();
        dictionaryDaoConfig.getIdentityScope().clear();
    }

    public TableDao getTableDao() {
        return tableDao;
    }

    public SequnceDao getSequnceDao() {
        return sequnceDao;
    }

    public CompanyDao getCompanyDao() {
        return companyDao;
    }

    public ZoneDao getZoneDao() {
        return zoneDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public CategoryGroupDao getCategoryGroupDao() {
        return categoryGroupDao;
    }

    public BrandDao getBrandDao() {
        return brandDao;
    }

    public GenericDao getGenericDao() {
        return genericDao;
    }

    public EngineDao getEngineDao() {
        return engineDao;
    }

    public SerieEnginesDao getSerieEnginesDao() {
        return serieEnginesDao;
    }

    public ManufacturerDao getManufacturerDao() {
        return manufacturerDao;
    }

    public SerieDao getSerieDao() {
        return serieDao;
    }

    public PartDao getPartDao() {
        return partDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public SupplierDao getSupplierDao() {
        return supplierDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public LinkDao getLinkDao() {
        return linkDao;
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

    public DictionaryDao getDictionaryDao() {
        return dictionaryDao;
    }

}
