package com.topway.fine.model;

import android.os.Parcel;
import android.os.Parcelable;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSONException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Dictionary".
 */
public class Dictionary implements Parcelable {

    private Long id;
    private String field;
    private Long value;
    private Long description;

    public Dictionary() {
    }

    public Dictionary(Long id) {
        this.id = id;
    }

    public Dictionary(Long id, String field, Long value, Long description) {
        this.id = id;
        this.field = field;
        this.value = value;
        this.description = description;
    }

    public void setDefaultValue() {
        if (this.id == null )
           this.id = new Long(0);
        if (this.field == null )
           this.field = "";
        if (this.value == null )
           this.value = new Long(0);
        if (this.description == null )
           this.description = new Long(0);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }

    public Long getValue() {
        return value;
    }

    public void setValue(Long value) {
        this.value = value;
    }

    public Long getDescription() {
        return description;
    }

    public void setDescription(Long description) {
        this.description = description;
    }


    //Parcelable
    protected Dictionary (Parcel in) {
        id = in.readLong();
        field = in.readString();
        value = in.readLong();
        description = in.readLong();
    }

    public static final Creator<Dictionary> CREATOR = new Creator<Dictionary>() {
        @Override
        public Dictionary createFromParcel(Parcel in) {
            return new Dictionary(in);
        }

        @Override
        public Dictionary[] newArray(int size) {
            return new Dictionary[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(id);
        dest.writeString(field);
        dest.writeLong(value);
        dest.writeLong(description);
    }
    //Parcelable END

    //JsonSerializable
    public static Dictionary fromJson(JSONObject jsonObject) throws JSONException {
        Dictionary domain = new Dictionary();

        domain.id = jsonObject.getLong("id");
        domain.field = jsonObject.getString("FIELD");
        domain.value = jsonObject.getLong("VALUE");
        domain.description = jsonObject.getLong("DESCRIPTION");

        return domain;
    }

    public static String toJson(Dictionary obj) throws JSONException {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("id",obj.id);
        jsonObject.put("FIELD",obj.field);
        jsonObject.put("VALUE",obj.value);
        jsonObject.put("DESCRIPTION",obj.description);
        return jsonObject.toString();
    }
    //JsonSerializable END

}
