package com.topway.fine.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EngineSeries".
 */
public class EngineSerie {

    private Long id;
    private Long engineId;
    private String engineName;
    private Long brandId;
    private String brandName;
    private Long serieId;
    private String serieName;
    private String memo;
    private Long hot;

    public EngineSerie() {
    }

    public EngineSerie(Long id) {
        this.id = id;
    }

    public EngineSerie(Long id, Long engineId, String engineName, Long brandId, String brandName, Long serieId, String serieName, String memo, Long hot) {
        this.id = id;
        this.engineId = engineId;
        this.engineName = engineName;
        this.brandId = brandId;
        this.brandName = brandName;
        this.serieId = serieId;
        this.serieName = serieName;
        this.memo = memo;
        this.hot = hot;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEngineId() {
        return engineId;
    }

    public void setEngineId(Long engineId) {
        this.engineId = engineId;
    }

    public String getEngineName() {
        return engineName;
    }

    public void setEngineName(String engineName) {
        this.engineName = engineName;
    }

    public Long getBrandId() {
        return brandId;
    }

    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    public String getBrandName() {
        return brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    public Long getSerieId() {
        return serieId;
    }

    public void setSerieId(Long serieId) {
        this.serieId = serieId;
    }

    public String getSerieName() {
        return serieName;
    }

    public void setSerieName(String serieName) {
        this.serieName = serieName;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Long getHot() {
        return hot;
    }

    public void setHot(Long hot) {
        this.hot = hot;
    }

}
