package com.topway.fine.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.topway.fine.model.Part;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Parts".
*/
public class PartDao extends AbstractDao<Part, Long> {

    public static final String TABLENAME = "Parts";

    /**
     * Properties of entity Part.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CategoryId = new Property(1, Long.class, "categoryId", false, "CATEGORY_ID");
        public final static Property BrandId = new Property(2, Long.class, "brandId", false, "BRAND_ID");
        public final static Property SerieId = new Property(3, Long.class, "serieId", false, "SERIE_ID");
        public final static Property EngineId = new Property(4, Long.class, "engineId", false, "ENGINE_ID");
        public final static Property Name = new Property(5, String.class, "name", false, "NAME");
        public final static Property Number = new Property(6, String.class, "number", false, "NUMBER");
        public final static Property Unit = new Property(7, String.class, "unit", false, "UNIT");
        public final static Property Image = new Property(8, String.class, "image", false, "IMAGE");
        public final static Property Hot = new Property(9, Long.class, "hot", false, "HOT");
    };

    private DaoSession daoSession;


    public PartDao(DaoConfig config) {
        super(config);
    }
    
    public PartDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"Parts\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CATEGORY_ID\" INTEGER DEFAULT(0) ," + // 1: categoryId
                "\"BRAND_ID\" INTEGER DEFAULT(0) ," + // 2: brandId
                "\"SERIE_ID\" INTEGER DEFAULT(0) ," + // 3: serieId
                "\"ENGINE_ID\" INTEGER DEFAULT(0) ," + // 4: engineId
                "\"NAME\" TEXT DEFAULT('') ," + // 5: name
                "\"NUMBER\" TEXT DEFAULT('') ," + // 6: number
                "\"UNIT\" TEXT DEFAULT('') ," + // 7: unit
                "\"IMAGE\" TEXT DEFAULT('') ," + // 8: image
                "\"HOT\" INTEGER DEFAULT(0) );"); // 9: hot
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Parts\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Part entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindLong(2, categoryId);
        }
 
        Long brandId = entity.getBrandId();
        if (brandId != null) {
            stmt.bindLong(3, brandId);
        }
 
        Long serieId = entity.getSerieId();
        if (serieId != null) {
            stmt.bindLong(4, serieId);
        }
 
        Long engineId = entity.getEngineId();
        if (engineId != null) {
            stmt.bindLong(5, engineId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(7, number);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(8, unit);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(9, image);
        }
 
        Long hot = entity.getHot();
        if (hot != null) {
            stmt.bindLong(10, hot);
        }
    }

    @Override
    protected void attachEntity(Part entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Part readEntity(Cursor cursor, int offset) {
        Part entity = new Part( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // categoryId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // brandId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // serieId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // engineId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // number
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // unit
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // image
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9) // hot
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Part entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCategoryId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setBrandId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setSerieId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setEngineId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setNumber(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUnit(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setImage(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setHot(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Part entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Part entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCategoryDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getBrandDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getSerieDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T3", daoSession.getEngineDao().getAllColumns());
            builder.append(" FROM Parts T");
            builder.append(" LEFT JOIN Categories T0 ON T.\"CATEGORY_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN Brands T1 ON T.\"BRAND_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN Series T2 ON T.\"SERIE_ID\"=T2.\"_id\"");
            builder.append(" LEFT JOIN Engines T3 ON T.\"ENGINE_ID\"=T3.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Part loadCurrentDeep(Cursor cursor, boolean lock) {
        Part entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Category category = loadCurrentOther(daoSession.getCategoryDao(), cursor, offset);
        entity.setCategory(category);
        offset += daoSession.getCategoryDao().getAllColumns().length;

        Brand brand = loadCurrentOther(daoSession.getBrandDao(), cursor, offset);
        entity.setBrand(brand);
        offset += daoSession.getBrandDao().getAllColumns().length;

        Serie serie = loadCurrentOther(daoSession.getSerieDao(), cursor, offset);
        entity.setSerie(serie);
        offset += daoSession.getSerieDao().getAllColumns().length;

        Engine engine = loadCurrentOther(daoSession.getEngineDao(), cursor, offset);
        entity.setEngine(engine);

        return entity;    
    }

    public Part loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Part> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Part> list = new ArrayList<Part>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Part> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Part> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
