package com.topway.fine.model;

import android.os.Parcel;
import android.os.Parcelable;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSONException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Sequnce".
 */
public class Sequnce implements Parcelable {

    private Long id;

    public Sequnce() {
    }

    public Sequnce(Long id) {
        this.id = id;
    }

    public void setDefaultValue() {
        if (this.id == null )
           this.id = new Long(0);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    //Parcelable
    protected Sequnce (Parcel in) {
        id = in.readLong();
    }

    public static final Creator<Sequnce> CREATOR = new Creator<Sequnce>() {
        @Override
        public Sequnce createFromParcel(Parcel in) {
            return new Sequnce(in);
        }

        @Override
        public Sequnce[] newArray(int size) {
            return new Sequnce[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(id);
    }
    //Parcelable END

    //JsonSerializable
    public static Sequnce fromJson(JSONObject jsonObject) throws JSONException {
        Sequnce domain = new Sequnce();

        domain.id = jsonObject.getLong("id");

        return domain;
    }

    public static String toJson(Sequnce obj) throws JSONException {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("id",obj.id);
        return jsonObject.toString();
    }
    //JsonSerializable END

}
