package com.topway.fine.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.topway.fine.model.Serie;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Series".
*/
public class SerieDao extends AbstractDao<Serie, Long> {

    public static final String TABLENAME = "Series";

    /**
     * Properties of entity Serie.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property GenericId = new Property(2, Long.class, "genericId", false, "GENERIC_ID");
        public final static Property BrandId = new Property(3, Long.class, "brandId", false, "BRAND_ID");
        public final static Property BrandName = new Property(4, String.class, "brandName", false, "BRAND_NAME");
        public final static Property EngineId = new Property(5, Long.class, "engineId", false, "ENGINE_ID");
        public final static Property EngineName = new Property(6, String.class, "engineName", false, "ENGINE_NAME");
        public final static Property Path = new Property(7, String.class, "path", false, "PATH");
        public final static Property Image = new Property(8, String.class, "image", false, "IMAGE");
        public final static Property Common = new Property(9, Long.class, "common", false, "COMMON");
        public final static Property Hot = new Property(10, Long.class, "hot", false, "HOT");
    };

    private DaoSession daoSession;


    public SerieDao(DaoConfig config) {
        super(config);
    }
    
    public SerieDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"Series\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT DEFAULT('') ," + // 1: name
                "\"GENERIC_ID\" INTEGER DEFAULT(0) ," + // 2: genericId
                "\"BRAND_ID\" INTEGER DEFAULT(0) ," + // 3: brandId
                "\"BRAND_NAME\" TEXT DEFAULT('') ," + // 4: brandName
                "\"ENGINE_ID\" INTEGER DEFAULT(0) ," + // 5: engineId
                "\"ENGINE_NAME\" TEXT DEFAULT('') ," + // 6: engineName
                "\"PATH\" TEXT DEFAULT('') ," + // 7: path
                "\"IMAGE\" TEXT DEFAULT('') ," + // 8: image
                "\"COMMON\" INTEGER DEFAULT(0) ," + // 9: common
                "\"HOT\" INTEGER DEFAULT(0) );"); // 10: hot
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Series\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Serie entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        Long genericId = entity.getGenericId();
        if (genericId != null) {
            stmt.bindLong(3, genericId);
        }
 
        Long brandId = entity.getBrandId();
        if (brandId != null) {
            stmt.bindLong(4, brandId);
        }
 
        String brandName = entity.getBrandName();
        if (brandName != null) {
            stmt.bindString(5, brandName);
        }
 
        Long engineId = entity.getEngineId();
        if (engineId != null) {
            stmt.bindLong(6, engineId);
        }
 
        String engineName = entity.getEngineName();
        if (engineName != null) {
            stmt.bindString(7, engineName);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(8, path);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(9, image);
        }
 
        Long common = entity.getCommon();
        if (common != null) {
            stmt.bindLong(10, common);
        }
 
        Long hot = entity.getHot();
        if (hot != null) {
            stmt.bindLong(11, hot);
        }
    }

    @Override
    protected void attachEntity(Serie entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Serie readEntity(Cursor cursor, int offset) {
        Serie entity = new Serie( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // genericId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // brandId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // brandName
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // engineId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // engineName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // path
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // image
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // common
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // hot
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Serie entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGenericId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setBrandId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setBrandName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEngineId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setEngineName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPath(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setImage(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCommon(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setHot(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Serie entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Serie entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGenericDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getBrandDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getEngineDao().getAllColumns());
            builder.append(" FROM Series T");
            builder.append(" LEFT JOIN Generics T0 ON T.\"GENERIC_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN Brands T1 ON T.\"BRAND_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN Engines T2 ON T.\"ENGINE_ID\"=T2.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Serie loadCurrentDeep(Cursor cursor, boolean lock) {
        Serie entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Generic generic = loadCurrentOther(daoSession.getGenericDao(), cursor, offset);
        entity.setGeneric(generic);
        offset += daoSession.getGenericDao().getAllColumns().length;

        Brand brand = loadCurrentOther(daoSession.getBrandDao(), cursor, offset);
        entity.setBrand(brand);
        offset += daoSession.getBrandDao().getAllColumns().length;

        Engine engine = loadCurrentOther(daoSession.getEngineDao(), cursor, offset);
        entity.setEngine(engine);

        return entity;    
    }

    public Serie loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Serie> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Serie> list = new ArrayList<Serie>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Serie> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Serie> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
