package com.topway.fine.model;

import android.os.Parcel;
import android.os.Parcelable;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSONException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Suppliers".
 */
public class Supplier implements Parcelable {

    private Long id;
    private Long companyId;
    private Long goodId;
    private Float price;
    private Long quantity;
    private Long hot;

    public Supplier() {
    }

    public Supplier(Long id) {
        this.id = id;
    }

    public Supplier(Long id, Long companyId, Long goodId, Float price, Long quantity, Long hot) {
        this.id = id;
        this.companyId = companyId;
        this.goodId = goodId;
        this.price = price;
        this.quantity = quantity;
        this.hot = hot;
    }

    public void setDefaultValue() {
        if (this.id == null )
           this.id = new Long(0);
        if (this.companyId == null )
           this.companyId = new Long(0);
        if (this.goodId == null )
           this.goodId = new Long(0);
        if (this.price == null )
           this.price = new Float(0);
        if (this.quantity == null )
           this.quantity = new Long(0);
        if (this.hot == null )
           this.hot = new Long(0);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getGoodId() {
        return goodId;
    }

    public void setGoodId(Long goodId) {
        this.goodId = goodId;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public Long getQuantity() {
        return quantity;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    public Long getHot() {
        return hot;
    }

    public void setHot(Long hot) {
        this.hot = hot;
    }


    //Parcelable
    protected Supplier (Parcel in) {
        id = in.readLong();
        companyId = in.readLong();
        goodId = in.readLong();
        price = in.readFloat();
        quantity = in.readLong();
        hot = in.readLong();
    }

    public static final Creator<Supplier> CREATOR = new Creator<Supplier>() {
        @Override
        public Supplier createFromParcel(Parcel in) {
            return new Supplier(in);
        }

        @Override
        public Supplier[] newArray(int size) {
            return new Supplier[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(id);
        dest.writeLong(companyId);
        dest.writeLong(goodId);
        dest.writeFloat(price);
        dest.writeLong(quantity);
        dest.writeLong(hot);
    }
    //Parcelable END

    //JsonSerializable
    public static Supplier fromJson(JSONObject jsonObject) throws JSONException {
        Supplier domain = new Supplier();

        domain.id = jsonObject.getLong("id");
        domain.companyId = jsonObject.getLong("COMPANY_ID");
        domain.goodId = jsonObject.getLong("GOOD_ID");
        domain.price = jsonObject.getFloat("PRICE");
        domain.quantity = jsonObject.getLong("QUANTITY");
        domain.hot = jsonObject.getLong("HOT");

        return domain;
    }

    public static String toJson(Supplier obj) throws JSONException {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("id",obj.id);
        jsonObject.put("COMPANY_ID",obj.companyId);
        jsonObject.put("GOOD_ID",obj.goodId);
        jsonObject.put("PRICE",obj.price);
        jsonObject.put("QUANTITY",obj.quantity);
        jsonObject.put("HOT",obj.hot);
        return jsonObject.toString();
    }
    //JsonSerializable END

}
