package com.topway.fine.model;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Zones".
 */
public class Zone {

    private Long id;
    private String name;

    public Zone() {
    }

    public Zone(Long id) {
        this.id = id;
    }

    public Zone(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public void setDefaultValue() {
        if (this.id == null )
           this.id = new Long(0);
        if (this.name == null )
           this.name = "";
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


}
